FROM php:8.3-apache

RUN docker-php-ext-install pdo pdo_mysql

COPY docker/apache-vhost.conf /etc/apache2/sites-available/000-default.conf
COPY . /var/www/html/

RUN mkdir -p /var/www/html/storage/uploads \
    && chown -R www-data:www-data /var/www/html

EXPOSE 80
